---
title: "stastical modeling to understand data"
author: "Kousuke Kikuchi"
date: "June 24, 2015"
output: html_document
---

# 1. データを理解するために統計モデルを作る
- 統計モデルは観測データにうまく当てはめられた数理モデル
- 現象の背後にある法則を利用した予測が可能

### 1.1 統計モデル：なぜ「統計」なモデル？
-  統計モデル
    - 観察によってデータ化された現象を説明するために作られる
    - 確率分布が基礎的な部品であり、データのばらつきをを表現する手段である
    - データとモデルを対応づける手続きが準備されていて、モデルとデータにどれだけ当てはまっているのか定量的に評価できる
- 第一段階の情報消失
    - 観測・実験から対象の情報を取り出す
    - ここでは扱わない
- 第二段階の情報消失
    - ばらつきや誤差の無視

### 1.2 「ブラックボックスな統計解析」の悪夢
- モデリングの際の手順、パラメータの選択基準、リンク関数の選び方などは明確な基準に基づいて選ぶ
    - もし一点でも不明瞭な点があればその結果は信用するべきではない
    - よくわからないモデルにデータを入れれば何らかの結果が出てくるのは疑似科学の類

### 1.3 この本の内容：一般線形化モデルの導入とそのベイズ的拡張
- 一般化線形モデル（generalized  linear model）
    - 線形モデル（linear model）は正規分布を前提にしている
    - すべて正規分布を前提にするのはおかしいだろ！

### 1.4 この本に登場する訳語、記号、語法について
- 逸脱度（deviance）
- 残差逸脱度（residual deviance）
- 最大逸脱度（null deviance）
- 固定効果（fixed effects）
- ランダム効果（random effects）
- リンク関数（link function）
    - GLMの応答変数の平均と線形予測子を対応づける関数
- 応答変数(response variable)
    - 説明変数（explanatory variable）のこと
    